djangoProject2/urls.py
from django.contrib import admin
from django.urls import path, include
import restaurant, visitor
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('restaurant/', include(('restaurant.urls','restaurant'), namespace='restaurant')),
    path('visitor/', include(('visitor.urls', 'visitor'), namespace='visitor' )),
]

visitor/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.Home.preferenceList, name='home'),
    path('register/', views.Home.createPreferenceForm, name='register'),
    path('search/<int:pk>',  views.searchResultShow, name='search'),
    path('delete/',  views.Home.deletePreference, name='delete'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

visitor/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from restaurant.models import Ingredient, Menu
from accounts.models import User, Restaurant
from.form import PreferenceForm
from django.views import View
from itertools import chain


# from .form import PreferenceForm
from django.views.generic import (ListView,
                                  DetailView,
                                  CreateView,
                                  DeleteView,
                                  UpdateView)

# Create your views here.
# def home(request):
    # return HttpResponse('visitor')
#     return render(request, 'visitor/home.html')
    # form
    # form = PreferenceForm()
# def get_list(request):
#     ingredient_list = Ingredient.objects.all()
#     ingredients_category = Ingredient.objects.values('category').distinct()
#     context = {
#         'form': form,
#         'ingredient_list': ingredient_list,
#         'ingredients_category': ingredients_category,
#     }
#     return render(request, 'visitor/home.html', context)



class Home(View):
    form_class = PreferenceForm
    template_name = 'visitor/home.html'

    def preferenceList(request):
        # print("worked")
        user_id = request.user.id
        ingredient_id_taple = User.objects.filter(id=user_id).values_list('preference')
        ingredient_id = list(chain.from_iterable(ingredient_id_taple))
        # print(ingredient_id)
        preference_registered = Ingredient.objects.filter(id__in =  ingredient_id )
        ingredient_list = Ingredient.objects.all()
        ingredients_category = Ingredient.objects.values('category').distinct()
        print(list(preference_registered.values_list('Jp_name')))
        context = {
            'user_id': user_id,
            'preference': preference_registered,
            'preference_jp_list': list(preference_registered.values_list('Jp_name', flat=True)),
            'ingredient_list': ingredient_list,
            'ingredients_category': ingredients_category,
        }
        return render(request, 'visitor/home.html', context)



    def createPreferenceForm(request,  *args, **kwargs):
        if request.method =="POST":
            form = PreferenceForm(request.POST)
            # print(request.POST.getlist('ingredient_id'))
        # somehow it can register only one ingredient (last one)
            if form.is_valid():
                for p in request.POST.getlist('ingredient_id'):
                  user = User.objects.get(id=request.user.id)
                  user.preference.add(p)
                  user.save()
                return redirect('visitor:home')
        else:
            form = PreferenceForm()
            print("fail")

        context = {
            'form': form
        }

        return render(request, 'visitor/home.html', context)

    def deletePreference(request):
        if request.method =="POST":
            if 'delete_preference' in request.POST:

                user = User.objects.get(id=request.user.id)
                preference = request.POST['delete']
                preference_id = Ingredient.objects.filter(Jp_name=preference).values('id')
                user.preference.remove(list(preference_id)[0]["id"])
                user.save()

        return redirect('visitor:home')



def searchResultShow(request, pk):
    menus = Menu.objects.filter(cuisine_num = pk)
    user_id = request.user.id
    ingredient_id_taple = User.objects.filter(id=user_id).values_list('preference')
    ingredient_id = list(chain.from_iterable(ingredient_id_taple))
    preference_registered = Ingredient.objects.filter(id__in=ingredient_id).values_list('Jp_name')
    restaurant = Restaurant.objects.all()
    # ingredient_id = list(chain.from_iterable(menus.values_list('preference')))
    # ingredients = Ingredient.objects.filter(id__in=ingredient_id)
    print(restaurant)
    context = {
        'menus': menus,
        'preference': list(chain.from_iterable((preference_registered))),
        # 'ingredients': ingredients,
        'restaurants':restaurant,

    }

    return  render(request, 'visitor/search_result.html', context)

templates/visitor/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    {% load hebon %}

    <link href="{% static 'css/visitor_home.css' %}" rel="stylesheet" type="text/css" media="all">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>Welcome</title>

</head>
<body>

<div class="tabs">
    <input id="all" type="radio" name="tab_item" checked>
    <label class="tab_item" for="all">Register food preference</label>
    <input id="programming" type="radio" name="tab_item">
    <label class="tab_item" for="programming">Search Local Cuisine</label>
    <div class="tab_content" id="all_content">
        <h3>Your preference: Avoid</h3>
        <div class="contents">
            {% for p in preference %}
                <div class="item">
                <form action="{% url 'visitor:delete' %}" method='post'>
                    {% csrf_token %}
                    <input type="hidden" value={{ p.Jp_name }} name="delete">
                    <button name="delete_preference" class="delete-button"><i class="fa-solid fa-trash"></i></button>
                    <div class="tag">
                        {{ p.En_name }}
                    </div>
                </form>
                </div>

            {% endfor %}
        </div>
        <h3>Add Your Preference</h3>
        <form action='{% url 'visitor:register' %}' method='post' class='form'>
            <!-- ユーザー登録フォームを表示 -->
            {% csrf_token %}
            <input type="hidden" name="user_id" value={{ user_id }}>
            <ul>
                {% for category in ingredients_category %}
                <li>
                <details>
                <summary>{{ category.category | hebon }}</summary>
                <ul class="ingredient_list" >
                    {% for ingredient in ingredient_list %}
                        {% if ingredient.category == category.category and ingredient.Jp_name not in preference_jp_list %}
                            <li class="ingredient_item"><input type="checkbox" name="ingredient_id"  value={{ ingredient.id }}><p>{{ ingredient.En_name }}</p></li>
                        {% endif %}
                    {% endfor %}
                </ul>
                </details>
                 </li>
                {% endfor %}
            </ul>
            <div style="text-align: center">
                <button type='submit' class='register_button'>Register</button>
            </div>
        </form>

    </div>
    <div class="tab_content" id="programming_content">
        <div>
            <h2>Fukuoka's local cuisine</h2>
        </div>
        <ul class="bl_flexContainer">
            <li class="el_flexItem">
                <div class="box">
                    <img src="https://www.japan-guide.com/g9/4811_mentaiko.jpg" width="250" height="150" >
                    <h3>Mentaiko</h3>
                    <p>Mentaiko, the spicy version of salted cod roe (tarako), is a common Japanese food that can be
                        found nationwide accompanying rice or alcohol, used as filling for rice balls, or as a seasoning
                        in pasta dishes. Mentaiko is particularly famous in Fukuoka, where it originated by way of Korea,
                        and is a typical menu item at the yatai food stalls and izakaya around the city where it is usually
                        served raw or lightly seared.
                    </p>
                    <p class="button"><a href="cuisine#1" class="button_01 -compact">Search Restaurant</a></p>
                </div>
            </li>
            <li class="el_flexItem">
                <div class="box">
                    <img src="https://www.japan-guide.com/g9/4811_motsunabe.jpg" width="250" height="150" >
                    <h3>Nabemono</h3>
                    <p>Nabemono is a compound word, where nabe (鍋) refers to a cooking pot and mono (物) means things or stuff. The concept of a nabe is simple: it can be a mixture of fresh vegetables, meat, seafood, tofu, and soybean products, or seasonal ingredients, all to be cooked in a simmering soup broth in a pot.
                        Motsunabe is a local hot pot dish typically made up of beef or pork tripe, cabbage, garlic,
                        chives and togarashi peppers in a soy sauce or miso based soup. The inexpensive, slightly spicy
                        stew is usually cooked at the table on portable burners and served together with a bowl of white
                        rice. Noodles or additional rice may be added to the leftover soup in the pot at the end of the
                        meal to finish the dish.
                    </p>
                    <p class="button"><a href="cuisine#2" class="button_01 -compact">Search Restaurant</a></p>
                </div>
            </li>
            <li class="el_flexItem">
                <div class="box">
                    <img src="https://www.japan-guide.com/g9/4811_gyoza.jpg" width="250" height="150" >
                    <h3>Gyoza</h3>
                    <p>Gyoza are pan-fried, Chinese style dumplings, which are typically stuffed with a mixture of
                        ground pork, cabbage and green onions. While gyoza appear on the menus of ramen-ya, izakaya and
                        other restaurants nationwide, they are also a popular Fukuoka specialty where they are served in
                        large batches on ceramic or hot iron plates. Fukuoka, or Hakata, style gyoza can be found at
                        specialty gyoza shops around the city, especially around Hakata Station.
                    </p>
                    <p class="button"><a href="cuisine#4" class="button_01 -compact">Search Restaurant</a></p>
                </div>
            </li>
            <li class="el_flexItem">
                <div class="box">
                    <img src="https://www.japan-guide.com/g9/4811_hakataramen.jpg" width="250" height="150" >
                    <h3>Noodle</h3>
                    <p>Noodles are a staple of Japanese cuisine. They are often served chilled with dipping sauces, or in soups or hot dishes.
                        Ramen is a Japanese noodle dish. Hakata Ramen is a local ramen dish that features thin noodles in a thick, creamy tonkotsu soup,
                        topped with slices of chashu. Some of the best places to enjoy Hakata Ramen are the city's
                        emblematic yatai food stalls. Hakata Ramen can also be found at any of the numerous ramen-ya in Fukuoka,
                        especially around Hakata Station.
                    </p>
                    <p class="button"><a href="{% url 'visitor:search' pk=3 %}" class="button_01 -compact">Search Restaurant</a></p>

                </div>
            </li>
        </ul>
    </div>
</div>

</body>
</html>

templates/visitor/search_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    {% load hebon %}
    <link href="{% static 'css/visitor_home.css' %}" rel="stylesheet" type="text/css" media="all">
    <link href="{% static 'css/visitor_menu.css' %}" rel="stylesheet" type="text/css" media="all">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>Title</title>

</head>
<body>

<div >
    <h2 style="text-align: center">Noodle</h2>
    {% for menu in menus  %}
        <ul class="bl_flexContainer">
            <li class="el_flexItem">
                <div class="box">
                    <div class="right">
                        <div class="photo">
                        <img src='../images/{{menu.photo}}'  width="250" height="150">
                        </div>
                    </div>
                    <div class="left">
                        <div>
                        NAME:{{ menu.name | hebon }}
                        </div>
                        <div>
    {#                    COOKING METHOD:{{ menu.method }}#}
                            COOKING METHOD: Boil
                        </div>
                        <div>
                        PRICE:{{ menu.price }}Yen
                        </div>
                        <div>
                        SERVINGS:{{ menu.num_people }}
                        </div>
                        <div>
                            INGREDIENTS:
                            {% for ingredient in menu.ingredient.all.values %}
                                {% if ingredient.Jp_name in preference %}
                                    <p style="color:coral">
                                    <i class="fa-solid fa-triangle-exclamation"></i>
                                    {{ ingredient.En_name  }},
                                    </p>
                                {%  else %}
                                    {{ ingredient.En_name  }},
                                {% endif %}
                            {% endfor %}
                        </div>
                        <div>
                            {% for restaurant in restaurants %}
                                {% if menu.Restaurant_id == restaurant %}
                                    RESTAURANT NAME:
                                    <a href={{ restaurant.address }}>
                                    {{ restaurant.name | hebon }}
                                    </a>
                                {% endif %}
                            {% endfor %}
                        </div>

                    </div>

                </div>
            </li>
        </ul>
    {% endfor %}

</div>

</body>
</html>