djangoProject2/urls.py
from django.contrib import admin
from django.urls import path, include
import restaurant, visitor
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('restaurant/', include(('restaurant.urls','restaurant'), namespace='restaurant')),
    path('visitor/', include(('visitor.urls', 'visitor'), namespace='visitor' )),
]

restaurant/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views



urlpatterns = [
    path('', views.home, name='home'),
    path('add/', views.AddMenuView.as_view(), name='add'),
    # path('add/category', views.category, name='category'),
    # path('add/category/<str:category>/', views.ingredient, name='ingredient'),
    path('edit/<slug:pk>/ingredient_add', views.EditMenuView.createIngredientsForm, name='ingredient'),
    path('edit/<slug:pk>/', views.EditMenuView.as_view(), name='edit'),
    path('edit/<slug:pk>/ingredient_delete', views.EditMenuView.deleteIngredient, name='delete_ingredient'),
    path('delete/<slug:pk>/', views.DeleteMenuView.as_view(), name='delete')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

visitor/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.Home.preferenceList, name='home'),
    path('register/', views.Home.createPreferenceForm, name='register'),
    path('search/<int:pk>',  views.searchResultShow, name='search'),
    path('delete/',  views.Home.deletePreference, name='delete'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurant/models.py
from django.db import models
# Create your models here.

class Ingredient(models.Model):
    Jp_name = models.TextField()
    category = models.TextField()
    En_name = models.TextField()

    def __str__(self):
        return self.Jp_name


class Menu(models.Model):
    Restaurant_id = models.ForeignKey('accounts.Restaurant', on_delete=models.CASCADE)
    name = models.CharField(max_length=1023)
    method = models.CharField(max_length=5)
    price = models.IntegerField()
    num_people = models.IntegerField()
    photo = models.ImageField(upload_to='')
    cuisine_num = models.IntegerField(blank=True, null=True)
    ingredient = models.ManyToManyField(Ingredient)


    def __str__(self):
        return self.name

restaurant/forms.py
from django import forms
from .models import Menu
import request


class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = ('name', 'method', 'price', 'num_people', 'photo', 'Restaurant_id')
    def __init__(self, *args, **kwargs):
        super(MenuForm, self).__init__(*args, **kwargs)
        self.fields['Restaurant_id'].initial = 2
        self.fields['Restaurant_id'].widget = forms.HiddenInput()

    name = forms.CharField(label="メニュー名")
    method = forms.CharField(label="調理方法")
    price = forms.IntegerField(label="価格")
    num_people = forms.IntegerField(label="人数")
    photo = forms.ImageField(label="料理の画像")



class IngredientsForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # for field in self.fields.values():
        #     field.widget.attrs['class'] = 'from-control'
    class Meta:
        model = Menu
        fields = ('id','ingredient',)

        # widgets = {
        #     'preference': forms.CheckboxSelectMultiple(),
        # }
TagInlineFormSet = forms.inlineformset_factory(
    Menu, Menu.ingredient.through, fields='__all__', can_delete=False
)
# class MenuIngredientForm(forms.ModelForm):
#     class Meta:
#         model = Menu_Ingredient
#         fields = ('menu', 'ingredient')
#     def __init__(self, *args, **kwargs):
#         menu = kwargs.pop('menu_id', None)
#         super(MenuIngredientForm, self).__init__(*args, **kwargs)
#         self.fields['menu'].initial = menu
#         self.fields['menu'].widget = forms.HiddenInput()

restaurant/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse
from accounts.models import Restaurant
from .models import Menu, Ingredient
from .forms import MenuForm, IngredientsForm
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from django.urls import reverse_lazy, reverse
from itertools import chain




# Create your views here.
def home(request):
    # return HttpResponse('restaurant')
    restaurant = request.user
    print(restaurant )
    menus = Menu.objects.filter(Restaurant_id=restaurant.id)
    restaurant_name = Restaurant.objects.get(user_id=restaurant.id)
    ingredient_list = Ingredient.objects.all()
    ingredients_category = Ingredient.objects.values('category').distinct()
    # print(menus)
    context = {
        'restaurant': restaurant_name.name,
        'menus': menus,
        'ingredient_list': ingredient_list,
        'ingredients_category': ingredients_category,
    }
    return render(request, 'restaurant/home.html', context)
#
class  AddMenuView(CreateView):
    model = Menu
    form_class = MenuForm
    template_name = 'restaurant/add.html'

    def get_context_data(self, **kwargs):
        context =super(AddMenuView, self).get_context_data(**kwargs)
        context['display_type'] = "none"
        return context

    def get_success_url(self):
        id = Menu.objects.last().id
        return reverse('restaurant:edit', kwargs={'pk':id,})


class EditMenuView(UpdateView):

    model = Menu
    form_class = MenuForm
    template_name = 'restaurant/edit.html'
    def get_context_data(self, **kwargs):
        context =super(EditMenuView, self).get_context_data(**kwargs)
        context['pk'] = self.kwargs['pk']
        context['display_type'] = "block"
        context['ingredients_id'] = list(chain.from_iterable(Menu.objects.filter(id=self.kwargs['pk']).values_list('ingredient')))
        # print(list(chain.from_iterable(context['ingredients_id'])))
        context['ingredient_list'] = Ingredient.objects.all()
        context['ingredients_category'] = Ingredient.objects.values('category').distinct()
        return context


    def createIngredientsForm(request,  *args, **kwargs):
        pk = kwargs['pk']

        if request.method == "POST":
            ingredient_form = IngredientsForm()
            # print(request.POST.getlist('ingredient_id'))
            if 'ingredient_id' in request.POST:
                ingredient_form = IngredientsForm(request.POST)
                # if ingredient_form.is_valid():
                #     print("3")
                    # form = MenuForm(request.POST)
                    # form.save()
                for p in request.POST.getlist('ingredient_id'):
                    menu = Menu.objects.get(id=pk)
                    menu.ingredient.add(p)

                    menu.save()

                    # return reverse('restaurant:edit', kwargs={'pk':pk})




        # context = {
        #     # 'ingredient_form': ingredient_form,
        #     'pk': int(pk),
        # }
        return redirect('restaurant:edit', pk=int(pk))

    def deleteIngredient(request,  *args, **kwargs):
        print("delete1")
        if request.method =="POST":
            if 'delete_ingredient' in request.POST:
                print("delete2")
                menu_id=kwargs['pk']
                menu=Menu.objects.get(id=menu_id)
                ingredient_id = request.POST['delete']
                print(ingredient_id)
                menu.ingredient.remove(ingredient_id)
                menu.save()

        return redirect('restaurant:edit', pk=int(menu_id))

    def get_success_url(self):
        # id = self.kwargs['pk']
        print("here")
        return reverse('restaurant:home')

class DeleteMenuView(DeleteView):
    model = Menu
    template_name = 'restaurant/confirm_delete.html'
    success_url = reverse_lazy('restaurant:home')





#
# def category(request):
#     restaurant = request.user
#     menus = Menu.objects.filter(Restaurant_id=restaurant.id)
#     ingredients = Ingredient.objects.all()
#     ingredients_category = Ingredient.objects.values('preference').distinct()
#     context = {
#         'restaurant': restaurant.first_name,
#         'menus': menus,
#         'ingredients':ingredients,
#         'ingredients_category':ingredients_category,
#     }
#     return render(request, 'restaurant/category.html', context)

templates/restaurant/add.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    {% load static %}
    {% load hebon %}
    {% load to_int %}
    <link href="{% static 'css/restaurant_add.css' %}" rel="stylesheet" type="text/css" media="all">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>Title</title>
</head>
<body>
<div class="from">
    <form enctype="multipart/form-data" method="post" class="menu_form">
        <div>
            {% csrf_token %}
            {{ form.as_ul }}
{#            <label>カテゴリ</label>#}
{#            <select name="example" style="font-size: 30px">#}
{#                <option>麺類</option>#}
{#                <option>鍋</option>#}
{#                <option>めんたい</option>#}
{#            </select>#}
        </div>
        <div>
            <button type="submit" style="margin-top:5%; margin-left: 40%;" >投稿</button>
        </div>

    </form>

</div>



</body>
</html>

templates/restaurant/category.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% for category in ingredients_category %}
    <li><a href="{% url 'restaurant:ingredient' category=category.category %} ">{{ category.category }}</a></li>
{% endfor %}
</body>
</html>

templates/restaurant/confirm_delete.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>DeleteView削除確認画面</h1>
    <form method="post">
        {% csrf_token %}
        <p>{{ menu.name }}を削除しますか？</p>
        <input type="submit" value="削除する">
    </form>

</body>
</html>

templates/restaurant/edit.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    {% load static %}
    {% load hebon %}
    {% load to_int %}
    <link href="{% static 'css/restaurant_add.css' %}" rel="stylesheet" type="text/css" media="all">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>Title</title>
</head>
<body>
<div class="from">
    <div style="float:right">
    <label> 材料:</label>
    <br>
        <ul class="list list--2" >
        {% for ingredient in menu.ingredient.all.values %}
            <form action="{% url 'restaurant:delete_ingredient' pk %}" method='post'>
                {% csrf_token %}
                <li>
                    <input type="hidden" value={{ ingredient.id }} name="delete">
                    <button name="delete_ingredient" class="delete-button"><i class="fa-solid fa-xmark"></i></button>
                    <div class="tag">
                         {{ ingredient.Jp_name  }}
                    </div>
                </li>
            </form>
        {% endfor %}
        </ul>
    </div>
    <form enctype="multipart/form-data" method="post" class="menu_form">
        <div>
            {% csrf_token %}
            {{ form.as_ul }}
{#            <label>カテゴリ</label>#}
{#            <select name="example" style="font-size: 30px">#}
{#                <option>麺類</option>#}
{#                <option>鍋</option>#}
{#                <option>めんたい</option>#}
{#            </select>#}
        </div>
        <div>
            <button type="submit" style="margin-top:5%; margin-left: 40%;" >投稿</button>
        </div>

    </form>

</div>

<div class="ingredients_form"  style="display: {{ display_type }}">

    <details >
        <summary>材料追加</summary>
        <form  action='{% url 'restaurant:ingredient' pk  %}' method='post' class='form' id="add_ingredient" >
            <!--材料登録フォームを表示 -->
            {% csrf_token %}
{#            <input type="hidden" name="user_id" value={{ user_id }}>#}
            <ul>
                {% for category in ingredients_category %}
                <li>
                <details>
                <summary>{{ category.category }}</summary>
                <ul class="ingredient_list" >
                    {% for ingredient in ingredient_list %}
                        {% if ingredient.category == category.category and ingredient.id not in ingredients_id %}

                            <li class="ingredient_item"><input type="checkbox" name="ingredient_id"  value="{{ ingredient.id }}"><p>{{ ingredient.Jp_name }}</p></li>
                        {% endif %}
                    {% endfor %}
                </ul>
                </details>
                 </li>
                {% endfor %}
            </ul>
            <div style="text-align: center">
                <button type='submit' class='register_button'>材料登録</button>
            </div>
        </form>
    </details>
</div>


</body>
</html>

templates/restaurant/home.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link href="{% static 'css/visitor_home.css' %}" rel="stylesheet" type="text/css" media="all">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>Title</title>
</head>
<body>

<h2>{{ restaurant }}</h2>

    <div>
        {% for menu in menus %}
            <div>
            {{ menu.name }}
            </div>
{#            # i have no ide a why path is like that...#}
            <img src='../visitor/images/{{menu.photo}}'  width="250" height="150">


            <a href="{% url 'restaurant:edit' menu.pk %}"><i class="fa-solid fa-pen-to-square"></i></a>
            <a href="{% url 'restaurant:delete' menu.pk %}"><i class="fa-solid fa-trash"></i></a>
        {% endfor %}

    </div>
<div>
    <a href="{% url 'restaurant:add' %}"><i class="fa-solid fa-plus"></i></a>
</div>

</body>
</html>

templates/restaurant/ingredient.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{#{{ ingredients }}#}
{% for ingredient in ingredients %}
    <li>
{#        <a href="{% url 'restaurant:ingredient' ingredient %} ">{{ ingredient }}</a>#}
    </li>

{% endfor %}
</body>
</html>